services:
  # Backend API Service
  - type: web
    name: solar-loan-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: GEMINI_API_KEY
        sync: false  # This will need to be set manually in Render dashboard

  # Frontend Service
  - type: web
    name: solar-loan-frontend
    runtime: node
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        fromService:
          type: web
          name: solar-loan-backend
          property: host
