services:
  # Backend API Service
  - type: web
    name: solar-loan-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: GEMINI_API_KEY
        sync: false  # This will need to be set manually in Render dashboard
      - key: EIA_API_KEY
        value: EvfoVk7m9rgxL1meDiADYBT8mwISO0cXuSxoaW2K
      - key: EIA_URL
        value: https://api.eia.gov/v2/electricity/retail-sales/data
      - key: ZIPPOPOTAM_URL
        value: http://api.zippopotam.us/us/{zip}
      - key: FCC_LOOKUP_URL
        value: https://geo.fcc.gov/api/census/block/find
      - key: CENSUS_API_KEY
        value: 49430368095bb59d02bf3c8e1aa41dbf49591f38
      - key: CENSUS_API_URL
        value: https://api.census.gov/data/2021/acs/acs5
      # Note: Vantage Score now uses local Excel file instead of API

  # Frontend Service
  - type: web
    name: solar-loan-frontend
    runtime: node
    buildCommand: cd frontend && npm ci --include=dev && npm run build
    startCommand: cd frontend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        fromService:
          type: web
          name: solar-loan-backend
          property: host
